#! /usr/bin/env python
# Author: Thura Hlaing <trhura@gmail.com>
# Time-stamp: <2013-10-27 19:09:35 (trhura)>

__author__ = "Thura Hlaing <trhura@gmail.com>"

import sys
import os
import csv
import codecs

copyright = """<!--
/*
**
** Copyright 2013, Thura Hlaing <trhura@gmail.com>
**
** DO NOT EDIT
** Autogenerated by keyboard generator script. See scripts/ folder.
*/
-->"""

opening = """<?xml version="1.0" encoding="utf-8"?>
%(copyright)s
""" %locals()

keyboard_open = """
<Keyboard xmlns:android="http://schemas.android.com/apk/res/android"
  android:keyWidth="10%p"
  android:horizontalGap="0px"
  android:verticalGap="0px"
  android:keyHeight="@dimen/key_height">
"""

keyboard_close = """
</Keyboard>
"""

row_open = """
  <Row>
"""

row_close = """
  </Row>
"""

def main():
    for arg in sys.argv[1:]:
        if not os.path.exists (arg):
            print "%(arg)s file doesn't exists." %locals()
            sys.exit(-1)

        content = opening
        with open(arg, mode="r") as csvFile:
            content += keyboard_open

            csvReader = csv.reader(csvFile, delimiter="|", quotechar='"')
            for row in csvReader:
                if not row:
                    continue

                content += row_open

                indent = "    "
                for i, key in enumerate(row):
                    key_desc = "<Key "
                    if i == 0:
                        key_desc += 'android:keyEdgeFlags="left" '
                    elif (i + 1) == len(row):
                        key_desc += 'android:keyEdgeFlags="right" '

                    key = key.decode ('utf8').strip().strip('"')

                    attributes = []

                    if key[0] == u"[":
                        # array
                        assert key.find("]") != -1
                        codes_end=key.find("]")
                        codes = key[1:codes_end]
                        attributes = key[codes_end+1:].split(",")
                        key_desc += 'android:codes="%(codes)s" ' %locals()
                    else:
                        if key.find(",") == -1:
                            codes = key[0]
                        else:
                            codes_end = key.find(",")
                            codes = key[:codes_end]
                            attributes = key[codes_end:].split(",")

                        if len(codes) == 1:
                            codes = ord(codes)
                            key_desc += 'android:codes="%(codes)s" ' %locals()
                            key_desc += 'android:keyIcon="@drawable/sym_%(codes)s" ' %locals()
                        else:
                            key_desc += 'android:codes="@integer/key_%(codes)s" ' %locals()
                            key_desc += 'android:keyIcon="@drawable/sym_keyboard_%(codes)s" ' %locals()

                    attributes = format_attributes(attributes)
                    key_desc += attributes

                    key_desc += " />"

                    content += indent + key_desc + "\n"
                content += row_close

            content += keyboard_close

            filename, _ = os.path.splitext(arg)
            with codecs.open (filename + ".xml", "w", "utf8") as oFile:
                oFile.write(content)

def format_attributes(attributes):
    _attributes = []
    for attr in attributes:
        if not attr:
            continue

        assert attr.find('=') != -1
        key, value = attr.split('=')
        key = key.strip()
        key = "android:" + key

        value = value.strip()
        value = '"%(value)s"' %locals()
        _attributes.append("%(key)s=%(value)s" %locals())

    return " ".join(_attributes)

if __name__ == "__main__":
    main()